### ISSUE TITLE
Seeing all stdout logs

### ISSUE THREAD

**Issue by knownasilya** [steelbrain/denode#2] opened 2016-04-19 15:07 UTC
Normally I see the logs from `morgan` middleware for express in the CL, but with denode I don't see those logs, only the explicit `console.log` messages. Any thoughts?

https://github.com/expressjs/morgan/blob/master/index.js#L130

**Comment by steelbrain** [comment] 2016-04-19 15:16
I might dig deep into the app's source soon but here's some things you should note
1. Result of calls to `console.log` is shown in developer tools only
2. Everything written to `process.stdout` or `process.stderr` is available in the terminal and not in the dev console, which is by design correct

**Comment by knownasilya** [comment] 2016-04-19 15:17
@steelbrain nothing seems to show up in the terminal if it's coming from the app. Seems like the app's `process.stdout` is swallowed somewhere..

The only thing I've seen in the terminal is 

> [26386:0418/161846:ERROR:CONSOLE(0)] "The given range isn't in document.", source: chrome-devtools://devtools/bundled/inspector.html?remoteBase=https://chrome-devtools-frontend.appspot.com/serve_file/@76745cbfbdac04e2fe3204f8b4f96ae7dc6bfcfa/&can_dock=&toolbarColor=rgba(223,223,223,1)&textColor=rgba(0,0,0,1)&experiments=true (0)

**Comment by steelbrain** [comment] 2016-04-19 15:19
I am able to repro, investigating

**Comment by steelbrain** [comment] 2016-04-19 15:58
This has been fixed with other `process.std*` fixes in `v1.1.0`, see the CHANGELOG for more info

**Closed as completed by steelbrain** 2016-04-19 15:58 UTC
Labels: bug

**Comment by knownasilya** [comment] 2016-04-19 17:10
Fix confirmed.
